package droolRule


import com.gupao.vip.drools.edu.entity.ParamInfo ;
import com.gupao.vip.drools.edu.entity.RuleResult;
import org.slf4j.Logger
import org.slf4j.LoggerFactory ;

dialect  "java"
rule "datatransfor1"
    when
        ParamInfo(murex3Id != null)
        ruleResult : RuleResult()
    then
        final Logger LOGGER = LoggerFactory.getLogger("datatransfor1 规则引擎") ;
        LOGGER.info("参数:murex3Id==null");
        ruleResult.setMsg("murex3Id is null");
end


rule "datatransfor2"
    when
        ParamInfo(settleType != null)
        p: ParamInfo(settleType != null)
        ruleResult : RuleResult()
    then
        final Logger LOGGER = LoggerFactory.getLogger("datatransfor2 规则引擎") ;
        LOGGER.info("参数:p"+p.toString());
        ruleResult.setMsg("settleType is null");
end