import com.gupao.vip.drools.edu.entity.ParamInfo ;
import com.gupao.vip.drools.edu.entity.RuleResult;
import org.slf4j.Logger
import org.slf4j.LoggerFactory ;

dialect  "java"
rule "datatransfor1"
    when
        paramInfo : ParamInfo(murex3Id != null)
        ruleResult : RuleResult()
    then
        final Logger LOGGER = LoggerFactory.getLogger("datatransfor1 规则引擎") ;
        LOGGER.info("参数:paramInfo"+paramInfo.toString());
        ruleResult.setMsg(paramInfo.toString());
end